### ISSUE TITLE
backend crashes on pause sometimes

### ISSUE THREAD

**Issue by jojomatik** [jojomatik/blockcluster#385]
**Describe the bug**
Sometimes the backend crashes if a server is paused.

**To Reproduce**
1. Enable pause on idle
2. Wait
3. If server pauses correctly, unpause it and try again.

```
/usr/games/blockcluster/backend/dist/backend/src/components/server.js:479
        this.proc.stdin.write(command + "\n");
                  ^
TypeError: Cannot read properties of null (reading 'stdin')
    at Server.writeConsoleCommand (/usr/games/blockcluster/backend/dist/backend/src/components/server.js:479:19)
    at /usr/games/blockcluster/backend/dist/backend/src/components/server.js:488:18
```

**Expected behavior**
No error is thrown.

**Screenshots**
Not applicable.

**Environment:**
 - Backend OS: Alpine Linux
 - Client Browser: Chrome
 - Version: 0.11.0-beta.9

**Additional context**
None.

**Comment by jojomatik** [comment]
Not sure how that happened, I can't reproduce the issue right now.

**Comment by jojomatik** [comment]
I've since paused servers a lot of times and still haven't run into this issue again. I think it was some kind of one-off problem. 

I will close this for now and reopen the issue if it occurs again.
