### ISSUE TITLE
Stop idle timeout if server is paused manually 

### ISSUE THREAD

**Issue by jojomatik** [jojomatik/blockcluster#395]
**Describe the bug**
The backend crashes if the server is already paused manually and the idle timeout is finished.

**To Reproduce**
1. Enable "Pause on Idle"
2. Restart the server
3. Pause the server as soon as it is started
4. Wait until the server is paused again by the timeout
5. See error

**Expected behavior**
Timeout is cancelled as soon as the pause button is pressed.

**Screenshots**
Not applicable.

**Environment:**
 - Backend OS: Alpine Linux
 - Client Browser: Chrome
 - Version: 0.11.1-beta.1

**Additional context**
```
/usr/games/blockcluster/backend/dist/backend/src/components/server.js:519
        this.proc.stdin.write(command + "\n");
                  ^
TypeError: Cannot read properties of null (reading 'stdin')
    at Server.writeConsoleCommand (/usr/games/blockcluster/backend/dist/backend/src/components/server.js:519:19)
    at /usr/games/blockcluster/backend/dist/backend/src/components/server.js:528:18
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by jojomatik** [comment]
The function that writes to `stdin` should also have a catch that prints the error to the console instead of crashing the entire backend.
